<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/10 0010
 * Time: 17:00
 */

namespace app\bis\controller;

class Basecontroller extends \app\common\controller\Commoncontroller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('bis', '', 'bis')) {
            $this->error('请先登录', '/index.php/bis/login/index');
        }
    }
}
